import { Project, MediaAsset, RenderJob, SavedWorkflow, PluginItem, AppNotification, HistoryItem } from "./types";

export const initialProjects: Project[] = [
  {
    id: "1",
    name: "Nebula Cinematic Trailer",
    updatedAt: "2 mins ago",
    createdAt: "Jul 01, 2026",
    thumbnail: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=400&q=80",
    aspectRatio: "16:9",
    resolution: "3840x2160 (4K)",
    fps: 24,
    tags: ["Sci-Fi", "Cinematic", "VFX"],
    pinned: true,
  },
  {
    id: "2",
    name: "Summer Fashion Campaign 2026",
    updatedAt: "1 hour ago",
    createdAt: "Jun 28, 2026",
    thumbnail: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=400&q=80",
    aspectRatio: "9:16",
    resolution: "1080x1920 (Vertical)",
    fps: 30,
    tags: ["Fashion", "Vertical", "Promo"],
    pinned: true,
  },
  {
    id: "3",
    name: "Cyberpunk City Loop",
    updatedAt: "4 hours ago",
    createdAt: "Jun 25, 2026",
    thumbnail: "https://images.unsplash.com/photo-1515621061946-eff1c2a352bd?auto=format&fit=crop&w=400&q=80",
    aspectRatio: "16:9",
    resolution: "1920x1080 (HD)",
    fps: 60,
    tags: ["3D", "Loop", "Motion"],
    pinned: false,
  },
  {
    id: "4",
    name: "Architectural Walkthrough",
    updatedAt: "1 day ago",
    createdAt: "Jun 20, 2026",
    thumbnail: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80",
    aspectRatio: "16:9",
    resolution: "3840x2160 (4K)",
    fps: 30,
    tags: ["ArchViz", "3D", "Lumen"],
    pinned: false,
  },
  {
    id: "5",
    name: "Ambient Lo-Fi Music Stream",
    updatedAt: "2 days ago",
    createdAt: "Jun 18, 2026",
    thumbnail: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80",
    aspectRatio: "1:1",
    resolution: "1080x1080 (Square)",
    fps: 24,
    tags: ["Audio", "Loop", "Sleek"],
    pinned: false,
  },
];

export const initialMedia: MediaAsset[] = [
  {
    id: "m1",
    name: "A001_C012_0630_A.mp4",
    type: "video",
    size: "450 MB",
    duration: "00:45",
    resolution: "3840x2160",
    addedAt: "2 hours ago",
  },
  {
    id: "m2",
    name: "Deep Space Ambient Base.wav",
    type: "audio",
    size: "82 MB",
    duration: "04:12",
    addedAt: "4 hours ago",
  },
  {
    id: "m3",
    name: "Cyberpunk_Female_Hero.fbx",
    type: "3d",
    size: "14.2 MB",
    addedAt: "1 day ago",
  },
  {
    id: "m4",
    name: "Hero_Broll_Mountains.mp4",
    type: "video",
    size: "280 MB",
    duration: "00:22",
    resolution: "1920x1080",
    addedAt: "1 day ago",
  },
  {
    id: "m5",
    name: "Studio_Portrait_Lighting_01.png",
    type: "image",
    size: "4.8 MB",
    resolution: "4000x3000",
    addedAt: "2 days ago",
  },
  {
    id: "m6",
    name: "Script_Revision_Final_v3.pdf",
    type: "document",
    size: "1.2 MB",
    addedAt: "3 days ago",
  },
];

export const initialRenderQueue: RenderJob[] = [
  {
    id: "r1",
    projectName: "Nebula Cinematic Trailer",
    format: "MP4 (H.264)",
    resolution: "3840x2160 (4K)",
    fps: 24,
    progress: 74,
    status: "rendering",
    eta: "01m 24s",
    priority: "high",
    elapsed: "03m 45s",
  },
  {
    id: "r2",
    projectName: "Summer Fashion Campaign 2026",
    format: "MOV (ProRes 422)",
    resolution: "1080x1920 (Vertical)",
    fps: 30,
    progress: 0,
    status: "idle",
    priority: "medium",
    elapsed: "00m 00s",
  },
  {
    id: "r3",
    projectName: "Cyberpunk City Loop",
    format: "GIF",
    resolution: "500x500 (Small)",
    fps: 30,
    progress: 100,
    status: "completed",
    priority: "low",
    elapsed: "00m 22s",
  },
];

export const initialWorkflows: SavedWorkflow[] = [
  {
    id: "w1",
    name: "Smart Transcription & Multi-Translate",
    description: "Transcribes dialogue, cleans up audio, and generates subtitle layers in English, Spanish, and Japanese.",
    nodesCount: 5,
    lastUsed: "4 hours ago",
    isFavorite: true,
  },
  {
    id: "w2",
    name: "Auto B-Roll & Visual Enhancer",
    description: "Analyzes primary speech tracks and suggests matching high-quality video assets with matching color correction.",
    nodesCount: 7,
    lastUsed: "Yesterday",
    isFavorite: true,
  },
  {
    id: "w3",
    name: "Audio Master & Dialog Isolator",
    description: "Separates primary dialogue from room reflections, background noise, and applies level compressor parameters.",
    nodesCount: 4,
    lastUsed: "3 days ago",
    isFavorite: false,
  },
];

export const initialPlugins: PluginItem[] = [
  {
    id: "p1",
    name: "Vocal Isolation Pro",
    description: "Ultra-low latency deep-learning background isolation and echo cancellation engine.",
    version: "2.4.1",
    developer: "StudioAudio Labs",
    installed: true,
    category: "Audio",
    downloads: "4.8k",
  },
  {
    id: "p2",
    name: "Volumetric Clouds & Fluid AI",
    description: "Generates high-performance smoke, cloud, and water physics layers on the GPU.",
    version: "1.0.8",
    developer: "VFXCore Systems",
    installed: true,
    category: "Visual Effects",
    downloads: "12.3k",
  },
  {
    id: "p3",
    name: "Gemini Smart Copilot integration",
    description: "Full IDE and command bar workspace automation using generative intelligence commands.",
    version: "3.0.0",
    developer: "Google DeepMind Labs",
    installed: true,
    category: "AI",
    downloads: "42.9k",
  },
  {
    id: "p4",
    name: "Unreal Engine 5 Live Link",
    description: "Direct frame-buffer live sync pipeline into Unreal virtual production cameras.",
    version: "1.5.0",
    developer: "Epic Team",
    installed: false,
    category: "3D",
    downloads: "8.2k",
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: "n1",
    title: "Render Completed",
    description: "Project 'Cyberpunk City Loop' export completed in 22 seconds.",
    type: "rendering",
    timestamp: "10m ago",
    read: false,
  },
  {
    id: "n2",
    title: "Cloud Backup Active",
    description: "Successfully synchronized 4.5 GB of media assets to remote server.",
    type: "system",
    timestamp: "1h ago",
    read: true,
  },
  {
    id: "n3",
    title: "Vocal Isolation Update",
    description: "Plugin Vocal Isolation Pro has a new security & patch release v2.4.2.",
    type: "system",
    timestamp: "1 day ago",
    read: true,
  },
];

export const initialHistory: HistoryItem[] = [
  { id: "h1", action: "Exported project 'Cyberpunk City Loop'", timestamp: "10 mins ago", user: "You", type: "ui" },
  { id: "h2", action: "AI prompt: 'Generate dynamic color grading for an eerie Sci-Fi mood'", timestamp: "32 mins ago", user: "You", type: "ai" },
  { id: "h3", action: "Applied LUT: 'Retro Kodak Edge 500T'", timestamp: "35 mins ago", user: "You", type: "edit" },
  { id: "h4", action: "Isolated voice track and decreased noise by 12dB", timestamp: "1 hour ago", user: "You", type: "edit" },
];
